
# Global options
baseURL = "https://dwil2444.github.io/"
canonifyURLs = false
copyright = "© 2025 by Dane Williamson. <a href='/privacy'>Privacy policy</a>."
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]
languageCode = "en"
theme = "hugo-coder"
title = "home"

disqusShortname = "mlbytes"

# Main menu
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
[[menu.main]]
    name = "Publications"
    url  = "/publications"
    weight = 2
[[menu.main]]
    name = "Teaching"
    url = "/teaching"
    weight = 3
[[menu.main]]
    name = "Blog"
    url  = "/posts"
    weight = 4
[[menu.main]]
    name = "CV"
    url = "/cv.pdf"
    weight = 5


# Customization options
[params]


avatarURL = "avatar.png"
description = "Dane Williamsons personal Website"
info = ["Dane Williamson", "Department of Computer Science", "University of Virginia"]


    [params.head]
        author = "Dane Williamson"
        custom_css = ""
        description = "Academic website for PhD Student"
        keywords = ["some", "keywords", "to", "describe", "this"]

    [params.navigation]
        show_navigation = true

    [params.footer]
        show_footer = true

    [params.typography]
        title_font = "Bree Serif"
        body_font = "Source Sans Pro"

    [params.colors]
        theme_color = "#333333"
        background_color = "#fcfbf9"
        text_color = "#333333"
        link_color = "#60c17d"

    [params.social]
        [params.social.email]
            name = "E-Mail"
            icon = "fa fa-2x fa-envelope"
            url = "mailto:dw3zn@virginia.edu"
            weight = 1
        [params.social.github]
            name = "GitHub"
            icon = "fa fa-2x fa-github"
            url = "https://github.com/dwil2444"
            weight = 2
        [params.social.google_scholar]
            name = "Google Scholar"
            icon = "fa fa-2x fa-google"
            url = "https://scholar.google.com/citations?user=CIJsx4UAAAAJ&hl=en"
            weight = 3
        [params.social.institution]
            name = "My institution"
            icon = "fa fa-2x fa-university"
            url = "https://engineering.virginia.edu/departments/computer-science"
            weight = 4
        [params.social.linkedin]
            name = "LinkedIn"
            icon = "fa fa-2x fa-linkedin"
            url = "https://www.linkedin.com/in/dane-a-williamson/"
            weight = 5
        [params.social.stackoverflow]
            name = "stackoverflow"
            icon = "fa fa-2x fa-stack-overflow"
            url = "https://stackoverflow.com/users/9922025/dane-williamson"
            weight = 6




# Options for Markdown renderer
[markup]

    [markup.goldmark.renderer]
        unsafe = true
        xHTML = true

    [markup.highlight]
        style = 'dracula'
